language: objective-c
rvm: 2.0.0
before_install:
  - gem install danger danger-xcode_summary xcpretty xcpretty-json-formatter
script:
  - xcodebuild -project ios/sdk/WeexSDK.xcodeproj test -scheme WeexSDKTests CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone 6' | XCPRETTY_JSON_FILE_OUTPUT=ios/sdk/xcodebuild.json xcpretty -f `xcpretty-json-formatter`
  - bundle exec danger